enum Types {
  LOGIN_REQUEST = "APP/AUTH/LOGIN/REQUEST",
  LOGIN_ERROR = "APP/AUTH/LOGIN/ERROR",
  LOGIN_SUCCESS = "APP/AUTH/LOGIN/SUCCESS",
  SIGNOUT_REQUEST = "APP/AUTH/SIGNOUT/REQUEST",
  SIGNOUT_SUCCESS = "APP/AUTH/SIGNOUT/SUCCESS",
  SIGNOUT_ERROR = "APP/AUTH/SIGNOUT/ERROR",
  SIGNUP_REQUEST = "APP/AUTH/SIGNUP/REQUEST",
  SIGNUP_SUCCESS = "APP/AUTH/SIGNUP/SUCCESS",
  SIGNUP_ERROR = "APP/AUTH/SIGNUP/ERROR"
}

export default Types;
